import dbclient from '../database/database';
import dotenv from 'dotenv';
import bcrypt from 'bcrypt';

dotenv.config();
const saltRounds: string = (process.env.SALT_ROUNDS as string);
const pepper: string = (process.env.PEPPER as string);

export type User = {
  //id: Number; // autogenerated by postgres
  firstname: string;
  lastname: string;
  password: string;
};

export class UserStore {
  async index(): Promise<User[]> {
    try {
        const conn = await dbclient.connect();
        const sql = 'SELECT * FROM users';
        const result = await conn.query(sql);
        conn.release;
        return result.rows;
    } catch (err) {
        throw new Error(`Cannot get users ${err}`);
    }
  }

  async show(id: string): Promise<User> {
    try {
        const sql = 'SELECT * FROM users WHERE id=($1)';
        const conn = await dbclient.connect();
        const result = await conn.query(sql, [id]);
        conn.release();
        return result.rows[0];
    } catch (err) {
        throw new Error(`Could not find user ${id}. Error: ${err}`);
    }
  }

  async create(u: User): Promise<User> {
    try {
      const conn = await dbclient.connect();
      const sql = 'INSERT INTO users (firstname, lastname, password_digest) VALUES($1, $2) RETURNING *';
      const hash = bcrypt.hashSync(
        u.password + pepper, 
        parseInt(saltRounds)
      );

      const result = await conn.query(sql, [u.firstname, u.lastname, hash]);
      const user = result.rows[0]
      conn.release();

      return user;
    } catch(err) {
      throw new Error(`Unable create user (${u.firstname + u.lastname}): ${err}`);
    }
  }

  async authenticate(name: string, password: string): Promise<User | null> {
    const conn = await dbclient.connect();
    const sql = 'SELECT password_digest FROM users WHERE name=($1)';

    const result = await conn.query(sql, [name]);
    console.log(password + pepper);

    if(result.rows.length) {
      const user = result.rows[0];
      console.log(user);

      if (bcrypt.compareSync(password + pepper, user.password_digest)) {
        return user;
      }
    }

    return null;
  }
}